print("What's your name?")
myName = input()
print('Marvelous ' + myName + ' is a great name.')
myLength = len(myName)
print('Did you know that your name is ' + str(myLength) + ' letters long? How remarkable.')
print("That's all. Have a stupendous day.")